apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  strategy: {}
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - image: pisckitama/python-app:v1.0.0
        name: python-app
        resources:
          requests:
            cpu: "200"
            memory: "256Mi"
          limits:
            cpu: "300"
            memory: "384Mi"
status: {}
