name: ci

on:
  push:
    paths:
        - src/**
    branches:
        - main

jobs:
  ci:    
    runs-on: ubuntu-latest
    steps:
      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Modify values file
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          cd /tmp
          curl -sSL -o yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x yq && sudo mv yq /usr/local/bin/yq
          yq --version
          yq -ei '.image.tag = "${{ needs.ci.outputs.commit_id }}"' chart/${{ vars.APP_NAME }}/values.yaml

      - name: Commit Changes
        uses: EndBug/add-and-commit@v10
        with:
          message: 'Update helm value of ${{ vars.APP_NAME }} with commit ${{ needs.ci.outputs.commit_id }}'
      - name: Install ArgoCD
        shell: bash
        run: |
          # Donwload & Install Argocd CLI
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      - name: ArgoCD App Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username ${{ vars.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync ${{ vars.APP_NAME }}
